// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl.ripple'], [], false);
goog.addDependency('/../../../../../../../lib/sources/controllers/ripplecontrol.js', ['zz.ui.mdl.RippleControl'], ['goog.Timer', 'goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component'], false);
