// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.ui.mdl.ripple'], [], false);
goog.addDependency('/../../../../../../../lib/sources/enums/const.js', ['zz.ui.mdl.ripple.enums.CONST'], [], false);
goog.addDependency('/../../../../../../../lib/sources/enums/css.js', ['zz.ui.mdl.ripple.enums.CSS'], [], false);
goog.addDependency('/../../../../../../../lib/sources/ripple.js', ['zz.ui.mdl.Ripple'], ['goog.Timer', 'goog.dom.classlist', 'goog.events.EventType', 'goog.style', 'goog.ui.Component'], false);
